to-do-list:
  image: ubuntu/demo
  volumes:
    - /Users/Eric/Documents/demo:/opt/demo/current
  environment:
    - BRANCH=master
  ports:
    - 3000:3000
  stdin_open: true
  entrypoint: /bin/bash
  links:
    - postgres:postgres

postgres:
  ports:
    - 5432:5432
  image: postgres
  expose:
    - 5432
  environment:
    - POSTGRES_PASSWORD=trust123
  volumes:
    - ../../shared/base-postgres.sql:/docker-entrypoint-initdb.d/base-postgres.sql:ro
